val zioSbtVersion = "0.0.0+524-5fdf568b-SNAPSHOT"

addSbtPlugin("ch.epfl.scala"                     % "sbt-bloop"                 % "2.0.5")
addSbtPlugin("ch.epfl.scala"                     % "sbt-scalafix"              % "0.13.0")
addSbtPlugin("com.eed3si9n"                      % "sbt-buildinfo"             % "0.12.0")
addSbtPlugin("com.github.sbt"                    % "sbt-unidoc"                % "0.5.0")
addSbtPlugin("com.github.sbt"                    % "sbt-ci-release"            % "1.6.1")
addSbtPlugin("com.github.cb372"                  % "sbt-explicit-dependencies" % "0.3.1")
addSbtPlugin("com.thoughtworks.sbt-api-mappings" % "sbt-api-mappings"          % "3.0.2")
addSbtPlugin("com.typesafe"                      % "sbt-mima-plugin"           % "1.1.4")
addSbtPlugin("de.heikoseeberger"                 % "sbt-header"                % "5.10.0")
addSbtPlugin("org.scala-js"                      % "sbt-scalajs"               % "1.17.0")
addSbtPlugin("org.scala-native"                  % "sbt-scala-native"          % "0.5.5")
addSbtPlugin("org.scalameta"                     % "sbt-mdoc"                  % "2.6.1")
addSbtPlugin("org.scalameta"                     % "sbt-scalafmt"              % "2.5.2")
addSbtPlugin("pl.project13.scala"                % "sbt-jcstress"              % "0.2.0")
addSbtPlugin("pl.project13.scala"                % "sbt-jmh"                   % "0.4.7")
addSbtPlugin("nl.thijsbroersen"                  % "zio-sbt-ci"                % zioSbtVersion)
addSbtPlugin("nl.thijsbroersen"                  % "zio-sbt-ecosystem"         % zioSbtVersion)
addSbtPlugin("nl.thijsbroersen"                  % "zio-sbt-website"           % zioSbtVersion)
addSbtPlugin("com.eed3si9n"                      % "sbt-projectmatrix"         % "0.10.0")

resolvers ++= Resolver.sonatypeOssRepos("snapshots")
